home:
    path: /
    controller: App\Controller\ClientController::home
add_user:
    path: /ajouter-utilisateur
    controller: App\Controller\ClientController::add_user

list_clients:
  path: /list_clients
  controller: App\Controller\ClientController::list_clients

add_lender:
   path: /ajouter-preteur
   controller: App\Controller\AppController::add_lender

