#Route de l'appli
home:
    path: /
    controller: App\Controller\AppController::home

login:
  path: /login
  controller: App\Controller\SecurityController::login

home_admin:
  path: /home_admin
  controller: App\Controller\AppController::home_admin

home_lender:
  path: /home_lender
  controller: App\Controller\AppController::home_lender

home_user:
  path: /home_user
  controller: App\Controller\AppController::home_user



#Route des users
add_client:
    path: /add-client
    controller: App\Controller\ClientController::add_client

list_clients:
  path: /list-clients
  controller: App\Controller\ClientController::list_clients


delete_client:
  path: /delete-client/{id}
  controller: App\Controller\ClientController::delete_client

edit-client:
  path: /edit-client/{id}
  controller: App\Controller\ClientController::edit_client


#Route des preteurs
add_lender:
   path: /add-lender
   controller: App\Controller\ClientController::add_lender

list_lenders:
  path: /list-lenders
  controller: App\Controller\ClientController::list_lenders





#Route product
add_product:
  path: /add-product
  controller: App\Controller\ProductController::add_product

list_products:
  path: /list-products
  controller: App\Controller\ProductController::list_products

list_products_by_lender:
  path: /list-products-by-lender
  controller: App\Controller\ProductController::list_products_by_lender

delete_product:
  path: /delete-product/{id}
  controller: App\Controller\ProductController::delete_products

#Route Qr Code
qrcode_product:
  path: /qrcode-product/{id}
  controller: App\Controller\ProductController::genarateQRcode

qrcode_confirmation:
  path: /qrcode-confirmation/{id}
  controller: App\Controller\ProductController::confirmationQRcode


# Routes pour les emprunts

add_borrowing:
  path: /add-borrowing/{id}
  controller: App\Controller\BorrowingController::add_borrowing

list_borrowings:
  path: /list-borrowings
  controller: App\Controller\BorrowingController::list_borrowings

delete_borrowing:
  path: /delete-borrowing/{id}
  controller: App\Controller\BorrowingController::delete_borrowing
