home:
    path: /
    controller: App\Controller\AppController::home
add_user:
    path: /ajouter-utilisateur
    controller: App\Controller\AppController::add_user

list_obj:
  path: /objets
  controller: App\Controller\AppController::list_obj

add_product:
  path: /ajouter-objet
  controller: App\Controller\AppController::add_product

