#Route de l'appli
home:
    path: /
    controller: App\Controller\ClientController::home

connection:
  path: /conection
  controller: App\Controller\ClientController::connection

#Route des users
add_user:
    path: /ajouter-utilisateur
    controller: App\Controller\ClientController::add_user

list_clients:
  path: /list-clients
  controller: App\Controller\ClientController::list_clients


#Route des preteurs
add_lender:
   path: /add-lender
   controller: App\Controller\LenderController::add_lender

list_lenders:
  path: /list-lenders
  controller: App\Controller\LenderController::list_lenders

